### ISSUE TITLE
Add gtk-kn support to main

### ISSUE THREAD

**Issue by lexisother** [tau-OS/libhelium#34] opened 2023-04-26 10:01 UTC
### Problem

Currently, compilation of gtk-kn with libhelium `main` breaks.

Excuse the low quality image:
![image](https://user-images.githubusercontent.com/54973868/234541376-df2f7f07-4a93-4a4b-b6df-0d01f5a37af0.png)

The `v1.5.17` branch works, and is the version gtk-kn has pinned in their CI. Using the latest release, `v1.5.18`, and the `main` branch, results in the above errors.

### Proposal

Fix any errors related to the problem and make sure the `gir:run` task of gtk-kn succeeds.

**Comment by vbsteven** [comment] 2023-04-28 08:36
Seems to work fine now on latest gtk-kn `master` with latest helium `main` at  https://github.com/tau-OS/libhelium/commit/1183673f9daab553e63401c571220cb9261e96c3

**Comment by lexisother** [comment] 2023-04-28 09:05
Surprising. In that case you are free to increase the CI release tag to https://github.com/tau-OS/libhelium/releases/tag/1.5.18.

**Comment by leinardi** [comment] 2023-04-28 09:18
> you are free to increase the CI release tag to https://github.com/tau-OS/libhelium/releases/tag/1.5.18.

~That won't work because `1.5.18` does not include https://github.com/tau-OS/libhelium/commit/1183673f9daab553e63401c571220cb9261e96c3.~

~A new release is needed.~

**Comment by lexisother** [comment] 2023-04-28 09:30
Fairly certain that's not true.
![image](https://user-images.githubusercontent.com/54973868/235111216-daa8e2da-fc0f-4174-9a93-1b5dde56d646.png)

**Comment by leinardi** [comment] 2023-04-28 09:35
True, sorry, I didn't notice that the branch comparison is using a different sorting order from the commit list, and I assumed they were all showing the HEAD at the top:
![image](https://user-images.githubusercontent.com/273338/235112053-88d03dee-ab7d-479d-98b3-dd307427e49b.png)
![image](https://user-images.githubusercontent.com/273338/235112444-44c2e52a-b1bd-422b-beb4-5141a152fca9.png)

Ignore my previous comment.

**Comment by leinardi** [comment] 2023-04-28 09:39
@lexisother can you try again with the latest `master` of gtk-kn? Is it confirmed to be working also for you?

**Comment by lexisother** [comment] 2023-04-28 09:43
I will try when I am home. Give me until 6PM~ish CEST.

**Comment by lexisother** [comment] 2023-04-29 08:38
I can confirm it works on `master` of gtk-kn and `main` of libhelium at the time of writing.

**Comment by leinardi** [comment] 2023-04-29 08:41
Hey, out of curiosity I tried 1.5.19 and I get those errors from the screenshot. Maybe I'm still doing something wrong :see_no_evil:

**Comment by lexisother** [comment] 2023-04-29 08:44
This worked for me:
![image](https://user-images.githubusercontent.com/54973868/235293808-88bb8efb-d3d8-4c78-8b8b-6fb5e8be97dd.png)

**Comment by leinardi** [comment] 2023-04-29 08:57
Mmm, I'm o a different machine with Ubuntu 22.04 and here works... Maybe I messed up something in the other installation...

**Comment by lleyton** [comment] 2023-05-11 22:14
Should we close this now? I recently merged a pipeline to test bindings against each commit.. and I don't think there are any outstanding issues

**Comment by leinardi** [comment] 2023-05-15 08:04
I can't reproduce the issue anymore, I think it can be closed.

**Closed as completed** 2023-05-15 09:43 UTC
Labels: bug
